@echo off
echo Installing Visual Studio Community 2022...
winget install --id=Microsoft.VisualStudio.2022.Community -e
echo Installing CMake...
winget install --id=Kitware.CMake -e
echo Installing Vulkan SDK...
winget install --id=KhronosGroup.VulkanSDK -e
echo Installing Git…
winget install --id=Microsoft.Git -e
echo Development tools installed successfully.
pause